[package]
name = "stream_delimit"
version = "0.1.0"
authors = ["Sevag Hanssian <sevag.hanssian@gmail.com>"]
description = "length delimited protobuf stream separator"
repository = "https://github.com/sevagh/pqrs/tree/master/stream_delimit"
readme = "./README.md"
license = "MIT"
keywords = ["protobuf", "serde"]

[dependencies]
